eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DOCKER_HOST:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-40093102.okta.com/oauth2/default
    audience: api://default
